# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# SIMP 6.3      5.5      2.4.4  TBD***
# PE 2018.1     5.5      2.4.4  2020-05 (LTS)***
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5
---
language: ruby
cache: bundler
sudo: false

bundler_args: --without development system_tests --path .vendor

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

before_install:
  - rm -f Gemfile.lock
  - gem update --system

jobs:
  include:
    - stage: test
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 5.5.6"
      script:
        - bundle exec rake test

    - stage: test
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 5.5"
      script:
        - bundle exec rake test

    - stage: deploy
      rvm: 2.4.4
      if: 'fork = false AND tag = true'
      script:
        - true
      before_deploy:
        - "export PUPMOD_METADATA_VERSION=`ruby -r json -e \"puts JSON.parse(File.read('metadata.json')).fetch('version')\"`"
        - '[[ $TRAVIS_TAG =~ ^simp-${PUPMOD_METADATA_VERSION}$|^${PUPMOD_METADATA_VERSION}$ ]]'

      deploy:
        - provider: releases
          api_key:
            secure: "NyqAmraHQOTNVMDU4Di8LnCUvBXu+4aQnTO/TKlfdmgqHLToHfmAcFwBMc+6e1RBaAMqkHMEBJU1gMnvlpoBzfGyk4j3rBfkoT3pCWrWCGKt+0do0DRXxNrgNidKFo15TfYNsi06YMsCYe++m3igWnugpabIIptODPNhfOQ01/aamJSu2qhF2JtoAejCb4bd9pY2t0/sTnnbULZUsOFDBhCamQQEgZfTifjmcH6J3PpcOnI5jTukkytJetKymukU4x+Tw892XzQ8N2LiLYtgNjI0HabvqfhB7eG1/qDJHj8EoI3TeBdeAmhlvncGmsGrI4nlJeEHS1TQf8Foj6bCr+Q8GPoUm6e+uRjrX67X2kgNQsuhw73LiTaPHvb8vBmk5Rs2NRBJn3Qb8D///RXOkzcOvfIqJ+oU2tts6Q1DvMcatFGyJ0k/JHcsCTVOT7I2R4PXgeIyZCVQZYgnv5wMLlepuYyeaQdFEX1UXFBcfKYQiPW0QW9rVK8iCiNPffOgpxdXJ6wIxSUN4de8iXpnVBvqCz1HhnGTMNE+0f4n9b5XjiFUyDrG0NcXdUqMPTCSZurJeZEAzA1X/873/UdgODbveIVDZmSahv7MPG+9d6EzRSNa7gBloVVTL11nYRtQHEh+f7IzWiy69WWSmaBNu7MYJwMTC2tIiOdyeEE89gc="
          skip_cleanup: true
          on:
            tags: true
            condition: '($SKIP_FORGE_PUBLISH != true)'
        - provider: puppetforge
          user: simp
          password:
            secure: "sKbvgx/AZWB3C/m3vJ21cfrgvm4Xy0iFyzQ24hY1/Yhd17vBPFC3sb2QaZfM5tMqY+zo+kECIBX7U4FdZnCGG6OHoCsmstypS86jbOuc+gP0MD/VbMYEh7WzkiEkTqAJ3eOvSZHLGjHQhT3r7juzo1otnpSv4E/7Rm3TmrUKP5EhWu3YKgOQUPG47ipuuX0/yLBmKYg/4QDxHv0H/DyPSyO0KrgSsykPURvHhYT7seAe219fOm6xZZ6bJDdKwroMOHwrdUu4Jvwl94PdOSKcN8+/GaZUI+neY43L6P2BaEUPnjT3VrAuautZo1IlIK3PLZ/lLQcyugWw09eINPmX5fHnUHqzj3IO0JQ04+0MOIpcbnDe2Oujqm3eQqeZJN/+VoFNtlBQmkvKWgVki+C90Lj7ttsJRIkQFohjiTgzIpoyACIgo1DSLkbtsMEQNujvft5Kk8HLzMKpZ2LZuEuFWwkfmFoAhfWo6mk7Q7p0kaFcyUuSCZ1BjI8QtjWHrvcC/cFjrt553FJ/+eSFdM0vkP8SFdkeZuo83ocBrGKVP20qaE64Rymuw+HoN/EXjI3CILrr4rnWOoJTgnT6SfpiGKlBJgpgWjESFHbd7y4Xf6LepeFjy7P4Ir2LtwiVUYWsDSE222wy6jLnRibV9a/GjEiUXkouqURP9FCz2TkBnB4="
          on:
            tags: true
            condition: '($SKIP_FORGE_PUBLISH != true)'
